const data = [
  {
    "status": "on",
    "ipAddress": "192.168.120.18",
    "macAddress": "12:03:ff:22:de:d0",
    "hostName": "OT-001",
    "location": "Production Line",
    "type": "other",
    "os": "Ubuntu 22.04 LTS",
    "owner": "Eve Adams",
    "description": "A other located in Production Line."
  },
  {
    "status": "on",
    "ipAddress": "192.168.228.76",
    "macAddress": "c8:af:8a:6d:ee:24",
    "hostName": "OT-002",
    "location": "Data Center",
    "type": "other",
    "os": "Cisco IOS XE",
    "owner": "Alice Johnson",
    "description": "A other located in Data Center."
  },
  {
    "status": "on",
    "ipAddress": "192.168.186.119",
    "macAddress": "3a:7e:b1:21:0d:bf",
    "hostName": "OT-003",
    "location": "IT Closet",
    "type": "switch",
    "os": "FreeBSD",
    "owner": "Bob Williams",
    "description": "A switch located in IT Closet."
  },
  {
    "status": "on",
    "ipAddress": "192.168.119.199",
    "macAddress": "9a:7c:41:31:72:b5",
    "hostName": "OT-004",
    "location": "Data Center",
    "type": "wifi router",
    "os": "Debian",
    "owner": "John Doe",
    "description": "A wifi router located in Data Center."
  },
  {
    "status": "off",
    "ipAddress": "192.168.63.119",
    "macAddress": "9a:8c:d6:f4:43:31",
    "hostName": "OT-005",
    "location": "IT Closet",
    "type": "wifi router",
    "os": "Windows Server 2019",
    "owner": "Diana Prince",
    "description": "An inactive wifi router in IT Closet."
  },
  {
    "status": "off",
    "ipAddress": "192.168.240.231",
    "macAddress": "4c:3c:0e:9d:54:55",
    "hostName": "OT-006",
    "location": "Server Room",
    "type": "wifi router",
    "os": "FreeBSD",
    "owner": "John Doe",
    "description": "An inactive wifi router in Server Room."
  },
  {
    "status": "off",
    "ipAddress": "192.168.87.113",
    "macAddress": "dd:21:1c:fb:d3:95",
    "hostName": "OT-007",
    "location": "Remote Site",
    "type": "other",
    "os": "VxWorks",
    "owner": "Diana Prince",
    "description": "An inactive other in Remote Site."
  },
  {
    "status": "on",
    "ipAddress": "192.168.70.65",
    "macAddress": "4e:54:13:02:3e:93",
    "hostName": "OT-008",
    "location": "Data Center",
    "type": "server",
    "os": "FreeBSD",
    "owner": "Charlie Brown",
    "description": "A server located in Data Center."
  },
  {
    "status": "off",
    "ipAddress": "192.168.19.4",
    "macAddress": "b0:46:f0:3b:43:18",
    "hostName": "OT-009",
    "location": "Testing Lab",
    "type": "switch",
    "os": "Cisco IOS XE",
    "owner": "Bob Williams",
    "description": "An inactive switch in Testing Lab."
  },
  {
    "status": "on",
    "ipAddress": "192.168.236.7",
    "macAddress": "25:a5:8a:e5:a8:04",
    "hostName": "OT-010",
    "location": "IT Closet",
    "type": "wifi router",
    "os": "Ubuntu 22.04 LTS",
    "owner": "John Doe",
    "description": "A wifi router located in IT Closet."
  },
  {
    "status": "off",
    "ipAddress": "192.168.200.100",
    "macAddress": "5a:b4:89:e2:20:ba",
    "hostName": "OT-011",
    "location": "Testing Lab",
    "type": "wifi router",
    "os": "Cisco IOS XE",
    "owner": "Alice Johnson",
    "description": "An inactive wifi router in Testing Lab."
  },
  {
    "status": "off",
    "ipAddress": "192.168.129.96",
    "macAddress": "27:7e:f7:2e:ee:33",
    "hostName": "OT-012",
    "location": "Warehouse A",
    "type": "server",
    "os": "VxWorks",
    "owner": "John Doe",
    "description": "An inactive server in Warehouse A."
  },
  {
    "status": "off",
    "ipAddress": "192.168.224.16",
    "macAddress": "d4:91:22:c3:63:03",
    "hostName": "OT-013",
    "location": "Remote Site",
    "type": "other",
    "os": "VxWorks",
    "owner": "Alice Johnson",
    "description": "An inactive other in Remote Site."
  },
  {
    "status": "off",
    "ipAddress": "192.168.46.44",
    "macAddress": "51:76:03:07:7f:4a",
    "hostName": "OT-014",
    "location": "Lab Area",
    "type": "switch",
    "os": "Ubuntu 22.04 LTS",
    "owner": "Eve Adams",
    "description": "An inactive switch in Lab Area."
  },
  {
    "status": "off",
    "ipAddress": "192.168.163.153",
    "macAddress": "5f:bd:bf:94:db:e8",
    "hostName": "OT-015",
    "location": "Lab Area",
    "type": "wifi router",
    "os": "Windows Server 2019",
    "owner": "John Doe",
    "description": "An inactive wifi router in Lab Area."
  },
  {
    "status": "on",
    "ipAddress": "192.168.223.37",
    "macAddress": "8b:53:a0:c7:98:45",
    "hostName": "OT-016",
    "location": "Lab Area",
    "type": "other",
    "os": "Windows Server 2019",
    "owner": "Charlie Brown",
    "description": "A other located in Lab Area."
  },
  {
    "status": "off",
    "ipAddress": "192.168.136.109",
    "macAddress": "07:4b:01:a7:f8:13",
    "hostName": "OT-017",
    "location": "Production Line",
    "type": "wifi router",
    "os": "Debian",
    "owner": "Bob Williams",
    "description": "An inactive wifi router in Production Line."
  },
  {
    "status": "on",
    "ipAddress": "192.168.8.70",
    "macAddress": "82:0a:c0:e4:d5:82",
    "hostName": "OT-018",
    "location": "Server Room",
    "type": "wifi router",
    "os": "Ubuntu 22.04 LTS",
    "owner": "Jane Smith",
    "description": "A wifi router located in Server Room."
  },
  {
    "status": "on",
    "ipAddress": "192.168.203.76",
    "macAddress": "20:33:2f:45:de:b3",
    "hostName": "OT-019",
    "location": "Server Room",
    "type": "switch",
    "os": "Windows Server 2019",
    "owner": "Diana Prince",
    "description": "A switch located in Server Room."
  },
  {
    "status": "on",
    "ipAddress": "192.168.40.231",
    "macAddress": "e9:72:2f:c0:40:96",
    "hostName": "OT-020",
    "location": "Warehouse A",
    "type": "other",
    "os": "Cisco IOS XE",
    "owner": "John Doe",
    "description": "A other located in Warehouse A."
  },
  {
    "status": "on",
    "ipAddress": "192.168.87.45",
    "macAddress": "f0:10:b7:c7:3f:09",
    "hostName": "OT-021",
    "location": "Customer Desk",
    "type": "other",
    "os": "FreeBSD",
    "owner": "John Doe",
    "description": "A other located in Customer Desk."
  },
  {
    "status": "on",
    "ipAddress": "192.168.142.48",
    "macAddress": "80:af:52:90:7f:43",
    "hostName": "OT-022",
    "location": "Production Line",
    "type": "other",
    "os": "Debian",
    "owner": "Diana Prince",
    "description": "A other located in Production Line."
  },
  {
    "status": "on",
    "ipAddress": "192.168.13.154",
    "macAddress": "57:13:03:be:9e:59",
    "hostName": "OT-023",
    "location": "Warehouse A",
    "type": "other",
    "os": "VxWorks",
    "owner": "Charlie Brown",
    "description": "A other located in Warehouse A."
  },
  {
    "status": "off",
    "ipAddress": "192.168.42.21",
    "macAddress": "f6:e4:ee:f8:b2:fe",
    "hostName": "OT-024",
    "location": "Production Line",
    "type": "server",
    "os": "FreeBSD",
    "owner": "Jane Smith",
    "description": "An inactive server in Production Line."
  },
  {
    "status": "off",
    "ipAddress": "192.168.41.207",
    "macAddress": "9c:5d:00:b5:ce:eb",
    "hostName": "OT-025",
    "location": "Remote Site",
    "type": "switch",
    "os": "Cisco IOS XE",
    "owner": "Eve Adams",
    "description": "An inactive switch in Remote Site."
  },
  {
    "status": "on",
    "ipAddress": "192.168.218.44",
    "macAddress": "36:81:95:c2:96:27",
    "hostName": "OT-026",
    "location": "IT Closet",
    "type": "switch",
    "os": "FreeBSD",
    "owner": "Alice Johnson",
    "description": "A switch located in IT Closet."
  },
  {
    "status": "off",
    "ipAddress": "192.168.18.129",
    "macAddress": "e7:60:f5:96:f3:90",
    "hostName": "OT-027",
    "location": "Remote Site",
    "type": "other",
    "os": "Windows Server 2019",
    "owner": "Jane Smith",
    "description": "An inactive other in Remote Site."
  },
  {
    "status": "off",
    "ipAddress": "192.168.43.27",
    "macAddress": "2d:e7:aa:64:68:f5",
    "hostName": "OT-028",
    "location": "Remote Site",
    "type": "server",
    "os": "VxWorks",
    "owner": "Eve Adams",
    "description": "An inactive server in Remote Site."
  },
  {
    "status": "off",
    "ipAddress": "192.168.239.144",
    "macAddress": "c1:1f:30:1d:22:2c",
    "hostName": "OT-029",
    "location": "Testing Lab",
    "type": "other",
    "os": "Debian",
    "owner": "Bob Williams",
    "description": "An inactive other in Testing Lab."
  },
  {
    "status": "off",
    "ipAddress": "192.168.228.2",
    "macAddress": "80:fe:31:00:cd:cd",
    "hostName": "OT-030",
    "location": "Production Line",
    "type": "switch",
    "os": "Cisco IOS XE",
    "owner": "Charlie Brown",
    "description": "An inactive switch in Production Line."
  },
  {
    "status": "on",
    "ipAddress": "192.168.23.239",
    "macAddress": "19:fb:3e:46:e3:dd",
    "hostName": "OT-031",
    "location": "Lab Area",
    "type": "wifi router",
    "os": "FreeBSD",
    "owner": "Alice Johnson",
    "description": "A wifi router located in Lab Area."
  },
  {
    "status": "off",
    "ipAddress": "192.168.101.159",
    "macAddress": "21:67:e7:62:9b:a5",
    "hostName": "OT-032",
    "location": "Customer Desk",
    "type": "wifi router",
    "os": "VxWorks",
    "owner": "John Doe",
    "description": "An inactive wifi router in Customer Desk."
  },
  {
    "status": "on",
    "ipAddress": "192.168.70.60",
    "macAddress": "2c:58:c8:d0:15:5e",
    "hostName": "OT-033",
    "location": "Warehouse A",
    "type": "other",
    "os": "Debian",
    "owner": "John Doe",
    "description": "A other located in Warehouse A."
  },
  {
    "status": "on",
    "ipAddress": "192.168.208.93",
    "macAddress": "34:7a:f6:18:ac:5a",
    "hostName": "OT-034",
    "location": "Production Line",
    "type": "other",
    "os": "VxWorks",
    "owner": "John Doe",
    "description": "A other located in Production Line."
  },
  {
    "status": "on",
    "ipAddress": "192.168.111.35",
    "macAddress": "a3:fa:57:a8:c4:61",
    "hostName": "OT-035",
    "location": "Main Office",
    "type": "server",
    "os": "Cisco IOS XE",
    "owner": "John Doe",
    "description": "A server located in Main Office."
  },
  {
    "status": "off",
    "ipAddress": "192.168.218.189",
    "macAddress": "2f:76:16:92:b9:7a",
    "hostName": "OT-036",
    "location": "IT Closet",
    "type": "switch",
    "os": "Windows Server 2019",
    "owner": "Charlie Brown",
    "description": "An inactive switch in IT Closet."
  },
  {
    "status": "off",
    "ipAddress": "192.168.235.25",
    "macAddress": "58:4d:42:5d:f1:45",
    "hostName": "OT-037",
    "location": "Warehouse A",
    "type": "server",
    "os": "Windows Server 2019",
    "owner": "Eve Adams",
    "description": "An inactive server in Warehouse A."
  },
  {
    "status": "on",
    "ipAddress": "192.168.169.189",
    "macAddress": "93:7b:87:34:e5:bc",
    "hostName": "OT-038",
    "location": "Warehouse A",
    "type": "server",
    "os": "Windows Server 2019",
    "owner": "Diana Prince",
    "description": "A server located in Warehouse A."
  },
  {
    "status": "off",
    "ipAddress": "192.168.185.114",
    "macAddress": "9f:26:b8:d5:8e:be",
    "hostName": "OT-039",
    "location": "Data Center",
    "type": "wifi router",
    "os": "FreeBSD",
    "owner": "Bob Williams",
    "description": "An inactive wifi router in Data Center."
  },
  {
    "status": "off",
    "ipAddress": "192.168.247.250",
    "macAddress": "7d:f4:95:0e:13:a0",
    "hostName": "OT-040",
    "location": "Production Line",
    "type": "wifi router",
    "os": "Windows Server 2019",
    "owner": "Alice Johnson",
    "description": "An inactive wifi router in Production Line."
  },
  {
    "status": "off",
    "ipAddress": "192.168.63.51",
    "macAddress": "ab:97:97:a4:26:8e",
    "hostName": "OT-041",
    "location": "Production Line",
    "type": "switch",
    "os": "Debian",
    "owner": "Diana Prince",
    "description": "An inactive switch in Production Line."
  },
  {
    "status": "on",
    "ipAddress": "192.168.9.32",
    "macAddress": "4c:8c:ad:49:36:74",
    "hostName": "OT-042",
    "location": "Remote Site",
    "type": "other",
    "os": "Cisco IOS XE",
    "owner": "Bob Williams",
    "description": "A other located in Remote Site."
  },
  {
    "status": "off",
    "ipAddress": "192.168.217.227",
    "macAddress": "7d:bc:dd:6b:a8:26",
    "hostName": "OT-043",
    "location": "Main Office",
    "type": "other",
    "os": "Windows Server 2019",
    "owner": "Charlie Brown",
    "description": "An inactive other in Main Office."
  },
  {
    "status": "on",
    "ipAddress": "192.168.244.114",
    "macAddress": "0d:f0:af:50:58:b7",
    "hostName": "OT-044",
    "location": "IT Closet",
    "type": "wifi router",
    "os": "FreeBSD",
    "owner": "Diana Prince",
    "description": "A wifi router located in IT Closet."
  },
  {
    "status": "off",
    "ipAddress": "192.168.22.64",
    "macAddress": "19:f4:44:87:58:7e",
    "hostName": "OT-045",
    "location": "Main Office",
    "type": "other",
    "os": "Windows Server 2019",
    "owner": "Bob Williams",
    "description": "An inactive other in Main Office."
  },
  {
    "status": "on",
    "ipAddress": "192.168.144.238",
    "macAddress": "3a:dd:33:73:75:fd",
    "hostName": "OT-046",
    "location": "Server Room",
    "type": "wifi router",
    "os": "Windows Server 2019",
    "owner": "Charlie Brown",
    "description": "A wifi router located in Server Room."
  },
  {
    "status": "on",
    "ipAddress": "192.168.101.182",
    "macAddress": "f0:89:6c:6a:aa:08",
    "hostName": "OT-047",
    "location": "Lab Area",
    "type": "server",
    "os": "Windows Server 2019",
    "owner": "Eve Adams",
    "description": "A server located in Lab Area."
  },
  {
    "status": "on",
    "ipAddress": "192.168.202.167",
    "macAddress": "9e:cf:61:d8:9c:e5",
    "hostName": "OT-048",
    "location": "Lab Area",
    "type": "switch",
    "os": "Debian",
    "owner": "Jane Smith",
    "description": "A switch located in Lab Area."
  },
  {
    "status": "off",
    "ipAddress": "192.168.112.213",
    "macAddress": "38:17:6a:29:af:95",
    "hostName": "OT-049",
    "location": "Lab Area",
    "type": "wifi router",
    "os": "Debian",
    "owner": "Eve Adams",
    "description": "An inactive wifi router in Lab Area."
  },
  {
    "status": "off",
    "ipAddress": "192.168.38.238",
    "macAddress": "a3:4a:43:c1:67:8f",
    "hostName": "OT-050",
    "location": "IT Closet",
    "type": "server",
    "os": "FreeBSD",
    "owner": "Eve Adams",
    "description": "An inactive server in IT Closet."
  }
]


export default data;